changes for edit and delete
rjspykar/demo_flutter pull request #1
Opened 2024-08-22 17:09 UTC by Prachiashi

2024-08-22 17:10 UTC, Prachiashi commented
aaaaaa

2024-08-22 17:13 UTC, rjspykar requested changes
Implement delete functionality to remove row from delete button click

2024-08-29 05:50 UTC, rjspykar commented on lib/Bean/TODO.dart
> +    if (response.statusCode == 204) {
Why have you put statusCode as 204 ??

2024-08-29 05:54 UTC, rjspykar requested changes
i have some doubts. please explain it and send pr again.

2024-08-29 05:54 UTC, rjspykar commented on lib/StatefulWidget/todo_list.dart
Why is this file deleted ?

2024-08-29 05:54 UTC, rjspykar commented on lib/Bean/TODO.dart
> +    if (response.statusCode == 204) {
What is the reason behind putting statuscode as 204?

2024-08-31 18:34 UTC, merged

2024-08-31 18:34 UTC, rjspykar commented
First PR Merge